language: node_js
node_js:
  - 8.11.2
before_install:
  - YARN_VERSION=`node -pe "require('./package.json').engines.yarn"`
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
script:
  - yarn lint
  - yarn test
env:
  global:
  - secure: wpUTebIaDocWDccPxoESnrs4RmsR5PFU4XXS5NXBxBE+U3H+CNLbDJa3BZaW9qYiUH2px3jfVmMHGiFCwArhoN9GrfEHd+5zMSYpgBwpQpuxc75E2IDY/+HLUK1ncg1bemvowVz9cMYhEyTrAE4fFq/UicywLwIjTzlhmFJwXkeu45OMXSzS7IGY6KmZ2I1wURrYSVzbaE5dUxrbtGpAqcmbAgSUcvke2eh9PchAp9vPzF707oksVjl6wzrz9d4MBzJp+KvShPS0jEnLcjvyV75uWtegciTdhaxNKd8w4t0zCQqG0lrQNF+dF3KjkclST+pNfQNtzVbVoCfxAfgO05dt0LhDaIVWyAZaSA7Sj4kM4Wk8laAVwb73IqGsEclOYPyLPfr6qRY6M6HwWld3zxpas/nuv2dmO0kqQ2DgZGPu+4dayiksoZ9cbTqkQ08JVv4/kOejuVVJKwBOaxz/o7VAmyMvHmCsJ0iG58W1NxE+zYsOllaGqKq5Mdf1gwtr0FxYPEhZR8lsoa4IeP6qqmOOWfjuLMR4hrWEixRbOeEPwSB4QPonR1UenxP+U9Pj30FUrTZqhjIvDvePZecCCpWaMjS/Wqff7nIuIutoesDOnJQt6kvcnIy15khnbs+HBpL/GhNzC3zAZdYwaN+OgiMYRLqHjXKPL6RII7wfo/w=
before_deploy:
  - yarn clean
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
  target-branch: master
  allow-empty-commit: true
  local-dir: public/
